routes & controllers created for request models/functionality
hatchways/team-baguette pull request #47
Opened 2021-09-16 19:30 UTC by logan858

### What this PR does (required):
- updates app.js with new routes, creates the routes for /requests, and creates the controllers for getting, updating and creating requests.  

### Screenshots / Videos (required):
![image](https://user-images.githubusercontent.com/78234668/133673526-1cf99cf4-5a72-45a2-9c6a-a45285f3ca29.png)

![image](https://user-images.githubusercontent.com/78234668/133673563-54fc129c-ac2b-40a8-8eec-e5580e0eb191.png)

### Any information needed to test this feature (required):
- Will need front end api calls to hit requests route first 

### Any issues with the current functionality (optional):
- The current update, get & create mongoose methods dont have front end data, so all of the values being plugged into the documents are tentative.  Once the front end hooks up to the backend, there may need to be adjustments on how some of it functions.

2021-09-17 09:10 UTC, ezeilo-su requested changes
Great work on this one. Go through the comments I left, make those changes and request for another review.

2021-09-17 09:10 UTC, ezeilo-su commented on server/controllers/requests.js
> +    try {
First, validate all the required fields from the request body. If any is not provided, return a bad request response.

2021-09-17 09:10 UTC, ezeilo-su commented on server/controllers/requests.js
> +            sitter_id: req.body.sitter_id,
Ensure to update variable names with camelCase

2021-09-17 09:10 UTC, ezeilo-su commented on server/controllers/requests.js
> +function createReqs(req, res, next) {
Prefer decorating the function with the `async` keyword and use `await` when calling the function.

2021-09-17 09:10 UTC, ezeilo-su commented on server/controllers/requests.js
> +        Request.create({
Use `async/await`. It will be cleaner.

2021-09-17 09:10 UTC, ezeilo-su commented on server/routes/requests.js
> +module.exports = router;
:+1:

2021-09-17 22:48 UTC, rajivtitus commented on server/controllers/requests.js
> +        Request.find({sitter_id: req.body.id}, (err, post) => {
A user may either be a sitter or an owner. Why don't we query both fields here?

Eg: $or: [{ user: req.user.id }, { sitter: req.user.id }]

2021-09-19 18:23 UTC, logan858 commented on server/controllers/requests.js
> +}
moved to bottom

2021-09-19 18:24 UTC, logan858 commented on server/controllers/requests.js
> +        Request.find({sitter_id: req.body.id}, (err, post) => {
updated to req.body.sitterId

2021-09-19 18:30 UTC, logan858 commented on server/controllers/requests.js
> +        Request.find({sitter_id: req.body.id}, (err, post) => {
added a 'if' statement to check is sitterId was supplied by client.

2021-09-19 18:30 UTC, logan858 commented on server/controllers/requests.js
> +        Request.find({sitter_id: req.body.id}, (err, post) => {
updated with cC

2021-09-19 18:33 UTC, logan858 commented on server/controllers/requests.js
> +    }
I think I understand, I updated my condition to only check to see if accepted has been turned to true, and then the logic follows accordingly.

2021-09-19 18:35 UTC, logan858 commented on server/controllers/requests.js
> +        Request.updateOneAndUpdate({_id: req.body.id}, {
Right, I missed that, thank you.

2021-09-19 18:37 UTC, logan858 commented on server/controllers/requests.js
> +        )
updated

2021-09-19 18:43 UTC, logan858 commented on server/controllers/requests.js
> +    try {
added validation for required body fields

2021-09-19 18:44 UTC, logan858 commented on server/controllers/requests.js
> +            sitter_id: req.body.sitter_id,
updated to cC

2021-09-19 19:05 UTC, logan858 commented on server/controllers/requests.js
> +function createReqs(req, res, next) {
changed from callback to async/await, on updateReqs & createReqs functions.

2021-09-19 19:06 UTC, logan858 commented on server/controllers/requests.js
> +        Request.create({
changed from callback to async/await, on updateReqs & createReqs functions.

2021-09-19 19:17 UTC, logan858 commented on server/controllers/requests.js
> +        Request.find({sitter_id: req.body.id}, (err, post) => {
I updated to retrieve both requests made and received by the client.  This will allow the client to use the same function whether they are a sitter or an owner.

2021-09-20 20:33 UTC, rajivtitus commented on server/controllers/requests.js
> +function getReqs(req, res, next) {
Maybe update this function to use async/await syntax as well? (To have more consistent code structure)

2021-09-20 20:41 UTC, rajivtitus commented on server/routes/requests.js
> +router.route("/requests").get(protect, requestsCtrl.getReqs)
You can simplify the route names here from `/requests` to `/` as the `requestsRouter` already contains the route name :)

2021-09-20 20:44 UTC, rajivtitus commented on server/controllers/requests.js
> +        await Request.findOneAndUpdate({_id: req.body.id}, {
Note: Using the request body to send the `id` works but in the future please consider the usage of route/path parameters.

2021-09-20 20:47 UTC, rajivtitus commented on server/controllers/requests.js
> +        if (!req.body.userId || !req.body.sitterId || !req.body.start || !req.body.end) {
Note: In the future, please consider using a function/middleware to perform validation :)

Here's a good article on doing so: https://www.freecodecamp.org/news/how-to-make-input-validation-simple-and-clean-in-your-express-js-app-ea9b5ff5a8a7/

2021-09-20 20:48 UTC, rajivtitus reviewed
Looks good for a start! Just a couple of small comments to address. Please tag me in once it's done so that we can get this approved :)

2021-09-21 23:36 UTC, rajivtitus commented on server/controllers/requests.js
> +        let dogReqs = await Request.find({
You can use 'const' here instead of 'let'

2021-09-21 23:39 UTC, rajivtitus commented on server/controllers/requests.js
> +        if (req.params.type === 'sitter') {
Since we are querying both fields (sitterId and userId) above, do we still need this check?

2021-09-23 00:20 UTC, logan858 commented on server/controllers/requests.js
> +        let dogReqs = await Request.find({
updated

2021-09-23 02:04 UTC, rajivtitus commented on server/controllers/requests.js
> +        if (req.params.type === 'sitter') {
Good thinking! For the time being since we are focusing on one user as a sitter and the other as a dog owner, we should be good. However, in the case a user is a sitter and an owner wouldn't it be better to have all the requests so that we can put them into two different tabs on the FE? :)

2021-09-23 02:05 UTC, rajivtitus approved these changes
Thanks for making changes!

Just left you a comment about future implementation for this feature

2021-09-23 15:50 UTC, merged