Feature/profile settings
hatchways/team-baguette pull request #56
Opened 2021-09-22 12:49 UTC by luisreyesxv

### What this PR does (required):

- created a edit profile photo page. It displays the current avatar and has 2 basic buttons. One button is a form to receive a file. When they put the file, there is a preview of the image. After they confirm the upload, it sends the file to the backend, and then based on the response, updates the user with the new avatar The other button does the same, but deletes the avatar.
-updated the avatar display component, to take a user object, and either display their avatar or display a placeholder.
-created a basic switch for the settings to deal with the future components.

### Screenshots / Videos (required):
This is how the edit avatar page normally looks like
![normal edit avatar page](https://user-images.githubusercontent.com/64181033/134345124-678fcc9d-23a1-42aa-aa5c-771442a0af50.png)
This is after clicking the Upload photo button
![about to update avatar](https://user-images.githubusercontent.com/64181033/134345197-38028673-0e5d-41a3-9b4c-d4ae8ca0469f.png)
This is after confirming the upload
![avatar fully updated](https://user-images.githubusercontent.com/64181033/134345334-188d98a9-79aa-4f07-9a37-b6e4e16b2a14.png)

### Any information needed to test this feature (required):
- have a png or jpg file that is 1MB or less.
- -make sure the backend has the keys for AWS

### Any issues with the current functionality (optional):
-This is more of a heads up, but I created a basic link to just jump into the edit profile photo page.
-There is the same sidebar as the dashboard, and I made basic placeholder for the navbar above. They will probably want to be placed on a higher level, but I also wanted to account for some things, so the general placement of the components make sense

2021-09-22 14:35 UTC, ezeilo-su requested changes
Nice implementation. You can add a suitable spacing between the "cancel upload" button and the user avatar. Read the few comments that I left so you can address them before your code can be approved.
Happy coding!

2021-09-22 14:35 UTC, ezeilo-su commented on client/src/components/AvatarDisplay/AvatarDisplay.tsx
> +  // const avatarURL = `https://robohash.org/${user.email}.png`;
Remove unused code

2021-09-22 14:35 UTC, ezeilo-su commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +    setAvatarFile(file);
You could simply perform these lines if `e.target.files` is Truthy, and no need for the void return statement.

2021-09-22 14:35 UTC, ezeilo-su commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        setAvatarFile(undefined);
Does this have to be `undefined`? Why not use `null`.

2021-09-22 14:35 UTC, ezeilo-su commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +          console.error({ data });
This is not necessary

2021-09-22 14:35 UTC, ezeilo-su commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        console.error({ data });
This is not necessary

2021-09-22 14:35 UTC, ezeilo-su commented on client/src/pages/Settings/Settings.tsx
> +    // loading for a split seconds until history.push works
Remove comment please

2021-09-24 14:16 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +          console.error({ data });
some of these comments, just come from the way other components were handling api call promises. Tried to keep it the same due to the comment of an unknown issue. But I have removed it

2021-09-24 14:17 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        setAvatarFile(undefined);
changed it

2021-09-24 14:17 UTC, luisreyesxv commented on client/src/components/AvatarDisplay/AvatarDisplay.tsx
> +  // const avatarURL = `https://robohash.org/${user.email}.png`;
done

2021-09-24 14:18 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        console.error({ data });
see comment above

2021-09-24 14:22 UTC, luisreyesxv commented
changes were made, ready for review

2021-09-25 00:05 UTC, rajivtitus commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        alert(data.error.message);
Why don't you use the 'Snackbar' here and below to display messages on error/success

2021-09-25 00:06 UTC, rajivtitus commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +          alert(data.error.message);
Same as comment above

2021-09-25 00:14 UTC, rajivtitus commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        <p>
You can use a `Typography` here to remain consistent with MUI design

Eg: `<Typography component="p" variant="body1">`

2021-09-25 00:18 UTC, rajivtitus commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        <div className={classes.picture}>{displayAvatar()}</div>
I don't think we need to create two separate components for `displayAvatar` and `fileOrSubmit`. They are pretty small and I can't think of any cases where we will be reusing these specific components 😄

2021-09-25 00:21 UTC, rajivtitus commented on client/src/components/EditProfilePicture/useStyles.ts
> +    textAlign: 'center',
Some of these props can directly be assigned to the `Typography` component

Eg: `<Typography variant="h3" align="center">`

2021-09-25 00:22 UTC, rajivtitus commented on client/src/components/EditProfilePicture/useStyles.ts
> +  picture: {
You can use a `Box` component above and pass props to it

Eg: `<Box display="flex" alignItems="center">`

2021-09-25 00:27 UTC, rajivtitus commented on client/src/pages/Settings/Settings.tsx
> +export default function Settings(): JSX.Element {
Maybe call this component 'Profile Photo' or 'Photo'? We may have another component for settings which will contain the profile settings sidebar :)

2021-09-25 00:28 UTC, rajivtitus commented on client/src/pages/Settings/Settings.tsx
> +    initSocket();
Why are we initializing the socket here? You can remove it, unless there's any specific reason?

2021-09-25 00:31 UTC, rajivtitus commented on client/src/pages/Settings/Settings.tsx
> +      <CssBaseline />
You can include the `<CssBaseline />` just once within the `App.tsx` as it does a global reset. If you want to apply the baseline to the child components consider using the `ScopedCssBaselinecomponent` instead

2021-09-25 00:31 UTC, rajivtitus commented on client/src/pages/Settings/Settings.tsx
> +      <Grid item xs={12} style={{ backgroundColor: 'pink', marginBottom: '5em', padding: '2em' }}>
Please avoid the usage of inline styles

2021-09-25 00:33 UTC, rajivtitus commented on client/src/pages/Dashboard/Dashboard.tsx
> +        <Link to="/settings/profile_picture">Shortcut link to Profile_picture</Link>
Please use hyphenated case for route names

Eg: `edit-profile`

2021-09-25 00:42 UTC, rajivtitus commented on client/src/context/useAuthContext.tsx
> +    const tempUser = loggedInUser;
Objects are not primitive types, the `tempUser` variable stores a reference to the state which is being mutated in the next line (please avoid mutating the state in react) 

Instead you can copy the object: 
`const tempUser = {...loggedInUser}`

2021-09-25 00:43 UTC, rajivtitus commented
Good work! Left some comments for you to address :)

2021-09-26 10:06 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        alert(data.error.message);
changed it to a snackbar

2021-09-26 10:07 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +          alert(data.error.message);
change to a snackbar

2021-09-26 10:16 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +        <div className={classes.picture}>{displayAvatar()}</div>
merged them into one function

2021-09-26 10:19 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/useStyles.ts
> +    textAlign: 'center',
i just cleaned it up a bit

2021-09-26 11:01 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/useStyles.ts
> +  picture: {
changed it, and cleaned up the useStyle a bit

2021-09-26 11:12 UTC, luisreyesxv commented on client/src/pages/Settings/Settings.tsx
> +    initSocket();
sorry, all the components except for Edit profile were placed there as placeholders. I copied the dashboard component just so the page would have the appearance of the mocks. I've removed them since they won't be needed and adding the header and sidebar are part of existing tickets

2021-09-26 11:14 UTC, luisreyesxv commented on client/src/pages/Settings/Settings.tsx
> +      <CssBaseline />
addressed this in comment above

2021-09-26 11:14 UTC, luisreyesxv commented on client/src/pages/Settings/Settings.tsx
> +      <Grid item xs={12} style={{ backgroundColor: 'pink', marginBottom: '5em', padding: '2em' }}>
addressed this in comment above. But will remove the inline styling

2021-09-26 11:32 UTC, luisreyesxv commented on client/src/pages/Dashboard/Dashboard.tsx
> +        <Link to="/settings/profile_picture">Shortcut link to Profile_picture</Link>
fixed

2021-09-26 11:48 UTC, luisreyesxv commented on client/src/context/useAuthContext.tsx
> +    const tempUser = loggedInUser;
I changed it to a more appropriate if statement and setState statement

2021-09-26 11:49 UTC, luisreyesxv commented
ready for review

2021-09-28 00:06 UTC, rajivtitus commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +  const [snackbarMessage, setSnackbarMessage] = useState({ className: '', message: '', open: false });
Nice work adding class names to the Snackbar. I'm curious to know why we didn't use the Snackbar from the `useSnackbarContext` though? :)

2021-09-28 00:11 UTC, rajivtitus commented on client/src/components/EditProfilePicture/useStyles.ts
> +  picture: {
Just a reminder that you may have forgotten to address this comment with the relevant code changes

2021-09-28 00:12 UTC, rajivtitus commented on client/src/pages/Settings/Settings.tsx
> +      <CssBaseline />
Please remove this `CssBaseline` component here as it is not required

2021-09-28 00:17 UTC, rajivtitus reviewed
Thanks for making requested changes, you may have missed a comment or two (I've tagged you into those comments) 😄 

Note: Please also update the title of the PR to reflect the correct feature (this PR is specifically for the 'Profile Photo' component)

2021-09-28 10:34 UTC, luisreyesxv commented on client/src/components/EditProfilePicture/EditProfilePicture.tsx
> +  const [snackbarMessage, setSnackbarMessage] = useState({ className: '', message: '', open: false });
I completely missed that we had this component, just refactored to use the snackbarcontext

2021-09-28 10:38 UTC, luisreyesxv commented on client/src/pages/Settings/Settings.tsx
> +      <CssBaseline />
i removed the component

2021-09-28 10:44 UTC, luisreyesxv commented
ready for review

2021-09-28 18:06 UTC, rajivtitus approved these changes
LGTM! Thanks for making changes 👍🏽

2021-09-29 14:19 UTC, merged