Feature/profile details page
hatchways/team-baguette pull request #66
Opened 2021-09-29 21:16 UTC by luisreyesxv

### What this PR does (required):
- the page design for a profile details show page. This originally started as FE and IN
- partially shows the data of the requested profile
- is getting the information from the backend
-  small fix to server, fixing `Profile.findByUserIdPopulated` and `imageupload` middleware to find the associated profile, and attach it to the `req`.
- -small fix to `<AvatarDisplay />` so that it properly handles a user that is generated from the profile, which normally won't have all the same fields, and a normal user object

### Screenshots / Videos (required):
![main page](https://user-images.githubusercontent.com/64181033/135348112-d6d6ab96-5139-4bd4-a9a3-6900277c9b22.png)
![gallery modal](https://user-images.githubusercontent.com/64181033/135348127-8f21b48b-928b-4808-8a1c-5f8c46bc6d89.png)

### Any information needed to test this feature (required):
- As of right now, the page is working off of the user's id vs profile id.
- You need to have a user created in the model, and that user needs to have an id. There doesn't need to be pictures in the gallery(that is part of the profile), but it helps.

### Any issues with the current functionality (optional):
- This request started as getting the information from the backend and getting it to full functionality, but that was before I saw ticket #35. So there is partial integration. It is hitting a route and getting a profile back, and is filling out most of the fields, but things like the ratings, dates, and everything on the right card, is hardcoded.
- In addition, when I'm working on ticket #35, I will create a route so that it looks for profile based on id vs on user's id. as well as some kind of 404 page when profile isn't found.  But for now, the param needs to be the user's id.

2021-09-30 15:47 UTC, ezeilo-su requested changes
You've made good progress here. Only a few comments left for you to address.
Happy coding!

2021-09-30 15:47 UTC, ezeilo-su commented on client/src/components/ProfileDetails/ProfileBookingCard.tsx
> +            onClick={() => console.log(dropIn, dropOff)}
Remove this console message, please.

2021-09-30 15:47 UTC, ezeilo-su commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +      console.log(res);
Remove console.log

2021-09-30 15:47 UTC, ezeilo-su commented on client/src/components/ProfileDetails/MainProfileDetails.tsx
> +        <Grid item xs={2} key={`gallery-image-${index}`}>
:+1:

2021-09-30 15:47 UTC, ezeilo-su commented on server/middleware/imageUpload.js
> +  const profile = await Profile.findByUserIdPopulated(req.user._id)
Please could you explain more about this method `findByUserIdPopulated` to me?

2021-10-01 10:15 UTC, luisreyesxv commented on server/middleware/imageUpload.js
> +  const profile = await Profile.findByUserIdPopulated(req.user._id)
There are a few cases where we would need to find a profile by it's user id. Most of those cases we would also need some of the user's information. Instead of writing the code to find and get this info throughout the code, I thought it would be better to have abstract to it's own function. Also gives the added bonus of knowing that the user field will always be populated with the same fields.

In regards as to why I'm using it in multiUpload, it makes more sense than the alternative. In order to upload image gallery, they need to send us the jwt and confirm that they are an authorized user. Doing a route that took in a profile id could lead to either a situation where a user could edit the profile of someone else or (more likely) we'd have to do a validation where we make sure that the profile belongs to the user. Either way, leads us to find the profile in relation to the user. So this just makes that process simpler with stuff that would need to be passed anyways.

2021-10-01 10:37 UTC, luisreyesxv commented
ready for review

2021-10-05 15:59 UTC, rajivtitus commented on client/src/components/ProfileDetails/MainProfileDetails.tsx
> +        <Grid item xs={2} key={`gallery-image-${index}`}>
👍🏽

2021-10-05 16:03 UTC, rajivtitus approved these changes
Good work with this! 👍🏽

2021-10-05 23:38 UTC, merged